plugins {
    id 'java'
    id 'application'
    id 'org.springframework.boot' version '4.0.1'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.shrivardhan.springboot'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    // Spring Boot Core (exclude default logging)
    implementation('org.springframework.boot:spring-boot-starter') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
    // Log4j2 (correct SLF4J binding)
    implementation 'org.springframework.boot:spring-boot-starter-log4j2'

    // Spring JDBC
    implementation('org.springframework.boot:spring-boot-starter-jdbc') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
    runtimeOnly 'com.oracle.database.jdbc:ojdbc11:23.3.0.23.09'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

}

test {
    useJUnitPlatform()
}